# Generated by Django 3.2.3 on 2021-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('name', models.CharField(max_length=30)),
                ('problems', models.CharField(max_length=30)),
                ('tablet_mg', models.CharField(max_length=10)),
                ('age_limit', models.CharField(max_length=10)),
                ('morning', models.CharField(max_length=20)),
                ('afternoon', models.CharField(max_length=20)),
                ('night', models.CharField(max_length=20)),
            ],
        ),
    ]
