# Generated by Django 3.2.3 on 2021-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='age_limit',
            field=models.CharField(max_length=30),
        ),
    ]
