# Generated by Django 3.2.5 on 2021-07-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_lab_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab_report',
        ),
    ]
