# Generated by Django 3.2.5 on 2021-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_delete_lab_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Lab_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription_boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='report_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
