# Generated by Django 3.2.3 on 2021-07-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacy_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=30)),
                ('patient_id', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
