# Generated by Django 3.2.5 on 2021-07-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_pharmacy_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tablet',
        ),
    ]
