# Generated by Django 3.2.5 on 2021-07-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='pharmacy',
            field=models.CharField(default='kousi', max_length=30),
        ),
    ]
