# Generated by Django 3.2.5 on 2021-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_tablet_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy_orders',
            name='patient_email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pharmacy_orders',
            name='patient_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pharmacy_orders',
            name='patient_phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='pharmacy',
            field=models.CharField(max_length=30),
        ),
    ]
