# Generated by Django 3.2.5 on 2021-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_pharmacy_orders_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pharmacy_orders',
            name='doctor_email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
