# Generated by Django 3.2.5 on 2021-07-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20210712_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy_orders',
            name='doctor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacy_orders',
            name='doctor_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacy_orders',
            name='patient_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacy_orders',
            name='patient_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacy_orders',
            name='patient_phone',
            field=models.CharField(max_length=30),
        ),
    ]
