# Generated by Django 3.2.5 on 2021-07-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20210712_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pharmacy_orders',
            new_name='Pharmacyord',
        ),
    ]
