# Generated by Django 3.2.5 on 2021-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_reqpharmacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqpharmacy',
            old_name='Pharmacy_kumar',
            new_name='kousi',
        ),
        migrations.RenameField(
            model_name='reqpharmacy',
            old_name='pharmacy_kousi',
            new_name='kumar',
        ),
        migrations.RenameField(
            model_name='reqpharmacy',
            old_name='pharmacy_peter',
            new_name='peter',
        ),
        migrations.AddField(
            model_name='reqpharmacy',
            name='accepted_pharmacy',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reqpharmacy',
            name='pharmacy_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
