# Generated by Django 3.2.5 on 2021-07-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_auto_20210712_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqpharmacy',
            old_name='kousi',
            new_name='doctor_boolean',
        ),
        migrations.RemoveField(
            model_name='reqpharmacy',
            name='kumar',
        ),
        migrations.RemoveField(
            model_name='reqpharmacy',
            name='peter',
        ),
        migrations.AddField(
            model_name='reqpharmacy',
            name='doctor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reqpharmacy',
            name='patient_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reqpharmacy',
            name='recomended',
            field=models.CharField(default='', max_length=30),
        ),
    ]
