# Generated by Django 3.2.5 on 2021-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20210712_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqpharmacy',
            name='doctor_booln',
            field=models.BooleanField(default=False),
        ),
    ]
