# Generated by Django 3.2.5 on 2021-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_reqpharmacy_doctor_booln'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='severity',
            field=models.CharField(default='high', max_length=20),
        ),
    ]
