# Generated by Django 3.1.4 on 2021-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_auto_20210715_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30)),
                ('problems', models.CharField(max_length=30)),
                ('report_details', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
