# Generated by Django 3.1.4 on 2021-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_lab_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyord',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacyord',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
