# Generated by Django 3.1.4 on 2021-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_auto_20210715_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyord',
            name='payment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
