# Generated by Django 3.1.4 on 2021-07-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_pharmacyord_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='name',
        ),
    ]
