# Generated by Django 3.0.3 on 2022-02-14 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_auto_20210716_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b', message='Enter a valid email')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('SEX_FEMALE', 'Female'), ('SEX_MALE', 'Male'), ('SEX_UNSURE', 'Unsure')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[A-Za-z0-9@#$%^&+=]{8,}', message='password must be Alphanumeric(Ex:-Aasd@12s)')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[6789][0-9]{9,}', message='Enter a valid phone number')]),
        ),
    ]
